GET http://localhost:3000/estudiantes


###


GET http://localhost:3000/estudiantes/5e73d1d067c1fa4e80939f9c

####


DELETE http://localhost:3000/estudiantes/5e73cfca25a91a4a556b8162


###

POST http://localhost:3000/estudiantes
Content-Type: application/json

{
  "datos": {
      "nombres":"Andres",
      "apellidos": "Channel",
      "codigo": 1234
  }
}

###


PATCH http://localhost:3000/estudiantes/5e73d5b287a7cb55e8ae7460
Content-Type: application/json 

{
  "datos": {
      "nombres":"Camilo"
  }
}
